### ISSUE TITLE
Summary statistics do not work for selecting multiple measurements

### ISSUE THREAD

**Issue by tischi** [embl-cba/shinyHTM#4]
Example error:

![image](https://user-images.githubusercontent.com/2157566/94811275-733a3f00-03f5-11eb-9427-7678e9f55469.png)

@hmbotelho Do you have time to check/fix this?

**Comment by hmbotelho** [comment]
Checking this now

**Comment by hmbotelho** [comment]
Hey @tischi 
I fixed this but cannot push the changes with the command line.

```
remote: Permission to embl-cba/shinyHTM.git denied to hmbotelho.
fatal: unable to access 'https://github.com/embl-cba/shinyHTM.git/': The requested URL returned error: 403
```

Can you pls check that I can push to this repo?

**Comment by tischi** [comment]
Did you get an invitation?
![image](https://user-images.githubusercontent.com/2157566/95302374-2ab1d400-0882-11eb-933b-b8e2a5ce56ac.png)

**Comment by hmbotelho** [comment]
Just realized I got it but now it has expired :-(
